// src/styles.js

export const styles = {
    pageSubtitle: {
        fontSize: '18px',
        color: '#64748b',
        fontWeight: 500,
    },
    viewMoreContainer: {
        textAlign: 'center',
        marginTop: '32px'
    },
    viewMoreBtn: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        padding: '14px 28px',
        borderRadius: '12px',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 600,
        fontSize: '16px',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '8px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
        transition: 'transform 0.2s, box-shadow 0.2s'
    },
    profileDropdown: {
        position: 'absolute',
        top: '100%',
        right: 0,
        background: 'white',
        borderRadius: '12px',
        boxShadow: '0 8px 24px rgba(0,0,0,0.1)',
        zIndex: 1010,
        width: '200px',
        overflow: 'hidden',
        paddingTop: '10px'
    },
    profileDropdownItem: {
        padding: '12px 16px',
        cursor: 'pointer',
        fontSize: '14px',
        color: '#475569',
        fontWeight: 500
    },
    noPropertiesContainer: {
        textAlign: 'center',
        padding: '60px 20px',
        backgroundColor: '#f8f9fa',
        borderRadius: '16px',
        border: '2px dashed #e2e8f0'
    },
    noPropertiesText: {
        fontSize: '18px',
        color: '#64748b',
        marginBottom: '24px'
    },
    app: {
        fontFamily: "'Inter', 'Segoe UI', system-ui, sans-serif",
        minHeight: '100vh',
        backgroundColor: '#f8fafc',
    },
    header: {
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        position: 'sticky',
        top: 8,
        borderRadius: 20,
        zIndex: 1000,
        boxShadow: '0 4px 20px rgba(0,0,0,1)',
    },
    headerContent: {
        maxWidth: 1400,
        margin: '0 auto',
        padding: '16px 32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        fontSize: '28px',
        color: 'white',
        fontWeight: 800,
        cursor: 'pointer',
    },
    logoIcon: {
        fontSize: '32px',
    },
    nav: {
        display: 'flex',
        gap: '28px',
        alignItems: 'center',
    },
    navItem: {
        position: 'relative',
        cursor: 'pointer',
        padding: '12px 0',
    },
    navText: {
        fontSize: '16px',
        fontWeight: 600,
        color: 'white',
    },
    dropdown: {
        position: 'absolute',
        top: '100%',
        left: '-50px',
        backgroundColor: 'white',
        boxShadow: '0 20px 40px rgba(0,0,0,0.15)',
        borderRadius: '16px',
        padding: '24px',
        marginTop: '2px',
        minWidth: '650px',
        display: 'flex',
        gap: '32px',
        zIndex: 1000,
    },
    dropdownSection: {
        flex: 1,
    },
    dropdownTitle: {
        fontSize: '14px',
        fontWeight: 700,
        color: '#4f46e5',
        marginBottom: '16px',
        textTransform: 'uppercase',
    },
    dropdownItem: {
        padding: '10px 16px',
        cursor: 'pointer',
        borderRadius: '8px',
        fontSize: '14px',
        color: '#475569',
        fontWeight: 500,
        marginBottom: '4px',
    },
    authSection: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
    },
    userSection: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        background: 'rgba(255,255,255,0.1)',
        padding: '8px 16px',
        borderRadius: '12px',
    },
    userIcon: {
        fontSize: '18px',
    },
    userName: {
        fontWeight: 600,
        fontSize: '14px',
        color: 'white',
    },
    authButtons: {
        display: 'flex',
        gap: '12px',
    },
    btnIcon: {
        marginRight: '8px',
        fontSize: '16px',
    },
    postBtn: {
        background: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
        color: 'white',
        padding: '12px 24px',
        borderRadius: '12px',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 600,
        fontSize: '16px',
        display: 'flex',
        alignItems: 'center',
        transition: 'transform 0.2s, box-shadow 0.2s',
    },
    loginBtn: {
        backgroundColor: 'transparent',
        color: 'white',
        padding: '12px 20px',
        borderRadius: '12px',
        border: '2px solid rgba(255,255,255,0.3)',
        cursor: 'pointer',
        fontWeight: 600,
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        transition: 'background-color 0.2s, border-color 0.2s',
    },
    signupBtn: {
        background: 'white',
        color: '#667eea',
        padding: '12px 20px',
        borderRadius: '12px',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 600,
        fontSize: '14px',
        display: 'flex',
        alignItems: 'center',
        transition: 'transform 0.2s, box-shadow 0.2s',
    },
    container: {
        maxWidth: 1400,
        margin: '0 auto',
        padding: '24px 32px',
        minHeight: '80vh',
    },
    heroSection: {
        backgroundColor: '#e0f2fe',
        padding: '60px 40px',
        borderRadius: '24px',
        marginBottom: '40px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        overflow: 'hidden',
        position: 'relative',
    },
    heroContent: {
        maxWidth: '60%',
        zIndex: 2,
    },
    mainTitle: {
        fontSize: '48px',
        fontWeight: 800,
        color: '#1e293b',
        marginBottom: '16px',
    },
    titleGradient: {
        background: 'linear-gradient(90deg, #667eea 0%, #764ba2 100%)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
    },
    heroSubtitle: {
        fontSize: '20px',
        color: '#475569',
    },
    heroGraphics: {
        position: 'absolute',
        right: '50px',
        top: '50%',
        transform: 'translateY(-50%)',
        width: '300px',
        height: '300px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    floatingElement1: {
        position: 'absolute',
        fontSize: '50px',
        top: '10%',
        left: '10%',
        animation: 'float 6s ease-in-out infinite',
    },
    floatingElement2: {
        position: 'absolute',
        fontSize: '80px',
        top: '40%',
        right: '10%',
        animation: 'float 7s ease-in-out infinite 1s',
    },
    floatingElement3: {
        position: 'absolute',
        fontSize: '40px',
        bottom: '15%',
        left: '30%',
        animation: 'float 5s ease-in-out infinite 2s',
    },
    searchSection: {
        marginTop: '-100px',
        marginBottom: '60px',
        zIndex: 10,
        position: 'relative',
    },
    section: {
        marginBottom: '60px',
    },
    sectionTitle: {
        fontSize: '28px',
        fontWeight: 700,
        color: '#1e293b',
        marginBottom: '24px',
        display: 'flex',
        alignItems: 'center',
    },
    sectionIcon: {
        marginRight: '12px',
        fontSize: '28px',
    },
    areasGrid: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: '16px',
    },
    areaButton: {
        backgroundColor: 'white',
        color: '#334155',
        padding: '12px 24px',
        borderRadius: '12px',
        border: '1px solid #e2e8f0',
        cursor: 'pointer',
        fontWeight: 600,
        fontSize: '16px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        transition: 'transform 0.2s, box-shadow 0.2s, border-color 0.2s',
    },
    areaEmoji: {
        fontSize: '18px',
    },
    propertiesSection: {
        marginBottom: '60px',
        paddingTop: '20px',
    },
    tabContainer: {
        display: 'flex',
        marginBottom: '20px',
        borderBottom: '2px solid #e2e8f0',
    },
    tab: {
        padding: '12px 24px',
        fontSize: '16px',
        fontWeight: 600,
        cursor: 'pointer',
        border: 'none',
        backgroundColor: 'transparent',
        color: '#64748b',
        borderBottom: '3px solid transparent',
        transition: 'color 0.2s',
    },
    activeTab: {
        color: '#667eea',
        borderBottom: '3px solid #667eea',
    },
    sectionHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '24px',
    },
    clearSearchBtn: {
        backgroundColor: '#f1f5f9',
        color: '#475569',
        padding: '8px 16px',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 500,
        fontSize: '14px',
    },
    emptyState: {
        textAlign: 'center',
        padding: '60px 20px',
        backgroundColor: '#ffffff',
        borderRadius: '16px',
        border: '2px dashed #cbd5e1',
        marginTop: '32px',
    },
    emptyIcon: {
        fontSize: '48px',
        marginBottom: '16px',
    },
    emptyTitle: {
        fontSize: '24px',
        fontWeight: 700,
        color: '#1e293b',
        marginBottom: '8px',
    },
    emptyText: {
        fontSize: '16px',
        color: '#64748b',
        marginBottom: '24px',
    },
    statsSection: {
        padding: '40px 0',
        backgroundColor: '#f1f5f9',
        borderRadius: '24px',
        marginBottom: '40px',
    },
    statsGrid: {
        maxWidth: 1200,
        margin: '0 auto',
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '32px',
    },
    statCard: {
        textAlign: 'center',
        padding: '20px',
        backgroundColor: 'white',
        borderRadius: '16px',
        boxShadow: '0 8px 20px rgba(0,0,0,0.05)',
    },
    statIcon: {
        fontSize: '36px',
        marginBottom: '12px',
    },
    statNumber: {
        fontSize: '32px',
        fontWeight: 800,
        color: '#667eea',
        marginBottom: '4px',
    },
    statLabel: {
        fontSize: '16px',
        color: '#64748b',
    },
    // SearchResultsPage / MyPropertiesPage utility styles
    backButton: {
        backgroundColor: 'transparent',
        border: 'none',
        color: '#4f46e5',
        cursor: 'pointer',
        fontSize: '16px',
        fontWeight: 600,
        marginBottom: '20px',
        display: 'flex',
        alignItems: 'center',
        transition: 'opacity 0.2s',
    },
    backIcon: {
        marginRight: '8px',
    },
    pageHeader: {
        marginBottom: '32px',
        borderBottom: '2px solid #e2e8f0',
        paddingBottom: '16px',
    },
    pageTitle: {
        fontSize: '36px',
        fontWeight: 800,
        color: '#1e293b',
        marginBottom: '8px',
    },
    loadingContainer: {
        textAlign: 'center',
        padding: '80px 20px',
        backgroundColor: '#f8f9fa',
        borderRadius: '16px',
        marginTop: '32px',
    },
    spinner: {
        fontSize: '48px',
        marginBottom: '16px',
    },
    errorContainer: {
        textAlign: 'center',
        padding: '60px 20px',
        backgroundColor: '#fee2e2',
        borderRadius: '16px',
        border: '2px solid #f87171',
        color: '#dc2626',
        marginTop: '32px',
    },
    retryBtn: {
        marginTop: '20px',
        backgroundColor: '#dc2626',
        color: 'white',
        padding: '10px 20px',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 600,
        transition: 'background-color 0.2s',
    },
    statsBar: {
        display: 'flex',
        gap: '24px',
        marginBottom: '32px',
        padding: '24px',
        backgroundColor: '#f8fafc',
        borderRadius: '16px',
        border: '2px solid #e2e8f0',
    },
    statItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    statValue: {
        fontSize: '24px',
        fontWeight: 700,
        color: '#1e293b',
    },
    grid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
        gap: '2rem',
        marginTop: '1rem',
    },
};